[versions]
java = "25"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
spotless = "8.10.2"
palantir-java-format = "2.98.0"
springdoc = "3.1.1"

[libraries]
# Versions for Spring Boot artifacts are managed by the Spring Boot BOM.
spring-boot-h2console = { module = "org.springframework.boot:spring-boot-h2console" }
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-data-jdbc-test = { module = "org.springframework.boot:spring-boot-starter-data-jdbc-test" }
spring-boot-starter-security-test = { module = "org.springframework.boot:spring-boot-starter-security-test" }
spring-boot-starter-validation-test = { module = "org.springframework.boot:spring-boot-starter-validation-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
h2 = { module = "com.h2database:h2" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
spring-boot-starters = [
	"spring-boot-h2console",
	"spring-boot-starter-data-jdbc",
	"spring-boot-starter-security",
	"spring-boot-starter-validation",
	"spring-boot-starter-webmvc",
]
spring-boot-test-starters = [
	"spring-boot-starter-data-jdbc-test",
	"spring-boot-starter-security-test",
	"spring-boot-starter-validation-test",
	"spring-boot-starter-webmvc-test",
]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
